apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-db
spec:
  schedule: "35 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get-data
            image: quay.io/projectquay/clair-action:v0.0.8
            command:
            - /bin/sh
            - -c
            - clair-action update --db-path=/tmp/matcher.db
            volumeMounts:
            - name: vuln-store
              mountPath: /tmp
          restartPolicy: Never
          volumes:
          - name: vuln-store
            persistentVolumeClaim:
              claimName: vuln-store
