kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vuln-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: gp2
  volumeMode: Filesystem
